# Generated by Django 3.2.3 on 2023-05-22 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_alter_review_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.AddField(
            model_name='donation',
            name='keywords',
            field=models.ManyToManyField(related_name='donation_keywords', to='community.Keyword'),
        ),
        migrations.AddField(
            model_name='donation',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_review', to='community.review'),
        ),
        migrations.AddField(
            model_name='donation',
            name='users',
            field=models.ManyToManyField(related_name='donation_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
