# Generated by Django 3.2.3 on 2023-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('organization', models.JSONField(blank=True, default=dict, null=True)),
                ('active', models.BooleanField()),
                ('title', models.CharField(max_length=256)),
                ('summary', models.TextField()),
                ('themeName', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64)),
                ('funding', models.FloatField()),
                ('remaining', models.FloatField()),
                ('numberOfDonations', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('activities', models.TextField()),
                ('imageLink', models.URLField()),
                ('imageGallerySize', models.IntegerField(blank=True, null=True)),
                ('videos', models.JSONField(blank=True, default=list, null=True)),
                ('approvedDate', models.DateTimeField()),
                ('themes', models.JSONField()),
                ('image', models.JSONField()),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('original_title', models.CharField(max_length=100)),
                ('original_language', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('theme_id', models.CharField(max_length=50)),
                ('genre_ids', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
