# Generated by Django 3.2.3 on 2023-05-23 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('like_users', models.ManyToManyField(related_name='like_genres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('organization', models.JSONField()),
                ('active', models.BooleanField()),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('contactName', models.CharField(max_length=200)),
                ('contactAddress', models.CharField(max_length=200)),
                ('contactCity', models.CharField(max_length=200)),
                ('contactState', models.CharField(max_length=200)),
                ('contactPostal', models.CharField(max_length=200)),
                ('contactCountry', models.CharField(max_length=200)),
                ('contactUrl', models.URLField()),
                ('projectLink', models.URLField()),
                ('progressReportLink', models.URLField()),
                ('themeName', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('iso3166CountryCode', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=200)),
                ('goal', models.FloatField()),
                ('funding', models.FloatField()),
                ('remaining', models.FloatField()),
                ('numberOfDonations', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('need', models.TextField()),
                ('longTermImpact', models.TextField()),
                ('activities', models.TextField()),
                ('additionalDocumentation', models.URLField()),
                ('imageLink', models.URLField()),
                ('imageGallerySize', models.IntegerField()),
                ('videos', models.JSONField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('approvedDate', models.DateTimeField()),
                ('donationOptions', models.JSONField()),
                ('modifiedDate', models.DateTimeField()),
                ('numberOfReports', models.IntegerField()),
                ('dateOfMostRecentReport', models.DateTimeField()),
                ('themes', models.JSONField()),
                ('image', models.JSONField()),
                ('countries', models.TextField()),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_path', models.CharField(blank=True, max_length=200, null=True)),
                ('adult', models.BooleanField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('original_title', models.CharField(max_length=100)),
                ('original_language', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('theme_id', models.CharField(max_length=50)),
                ('genre_ids', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('like_users', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
